### ISSUE TITLE
Auth guard [api] is not defined.

### ISSUE THREAD

**Issue by rhanmiano** [nuwave/lighthouse-tutorial#19]
Have been following what's on the [Tutorial Page](https://lighthouse-php.com/tutorial/#installing-lighthouse) . When I try this on the `/graphql-playground`
```graphql
{
  user(id: 1) {
    id
    name
    email
  }
}
```
I get this error. 

![image](https://user-images.githubusercontent.com/31644925/131245655-f791e2c6-c990-41b6-adc8-2ce4ed17017e.png)

I am fairly new to laravel and graphql, and I am trying out Lighthouse. I think I am missing something. Maybe someone can point me to the right track. Thanks

Other information
PHP version: 7.4.23
Composer version: 2.1.6

**Comment by spawnia** [comment]
Since Laravel changed their default template to exclude the api guard, a fresh install of Lighthouse now fails
without changing the configuration. https://github.com/nuwave/lighthouse/pull/1930 restores that zero-config working experience by falling
back to the Laravel default guard if lighthouse.php configures an unknown guard.

**Comment by spawnia** [comment]
Fixed as of https://github.com/nuwave/lighthouse/releases/tag/v5.22.4

**Comment by rhanmiano** [comment]
Confirming that this is fixed now after running `composer update`.
